#!/bin/bash

echo "Waiting for postgres..."

while ! nc -z db 5432; do
  sleep 0.1
done

echo "PostgreSQL started"


gunicorn --bind :8000 --workers 3 app.wsgi:application
python3 manage.py wait_for_db
python3 manage.py migrate
celery -A app worker -l info
exec "$@"