# Generated by Django 3.2.15 on 2022-09-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='user_id',
            new_name='user',
        ),
    ]
