# Generated by Django 3.2.15 on 2022-09-16 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=180)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.doc')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.reference')),
            ],
        ),
    ]
